version: '3.7'

services:
  skeleton_service:
    container_name: skeletonApi
    build: ./skeleton-service
    volumes:
      - type: bind
        source: ./skeleton-service/app
        target: /app/
    ports:
      - "8081:8000"
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    networks:
      - net_skeleton_service

networks:
  net_skeleton_service:
    driver: bridge